version: '3'
services:
    php-fpm:
        container_name: php-fpm
        image: php:7.4.3-fpm
        env_file: ./env/web.env
        volumes:
            - ./php:/usr/app/php
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./php:/usr/app/php
            - ./flask:/usr/app/flask
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php-fpm