version: '3'
services:
    web:
        container_name: web
        build: .
        env_file:
            - ./env/web.env
        volumes:
            - .:/usr/src/app
        command: bash -c 'gunicorn -b 0.0.0.0:80 "appweb:create_app()"'
        ports:
            - 10000:5000
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./db/mongo:/data/db
            - ./config/mongod.conf:/etc/mongod.conf